// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: Rpc.proto

package Micros

import (
	"GoMicro-Project/Service/Model"
	"fmt"
	"github.com/golang/protobuf/proto"
	"math"
)

import (
	"context"
	"github.com/micro/go-micro/client"
	"github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for RpcService service

type RpcService interface {
	GetProdListRpc(ctx context.Context, in *Model.RpcRequest, opts ...client.CallOption) (*Model.RpcResponse, error)
}

type rpcService struct {
	c    client.Client
	name string
}

func NewRpcService(name string, c client.Client) RpcService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "Models"
	}
	return &rpcService{
		c:    c,
		name: name,
	}
}

func (c *rpcService) GetProdListRpc(ctx context.Context, in *Model.RpcRequest, opts ...client.CallOption) (*Model.RpcResponse, error) {
	req := c.c.NewRequest(c.name, "RpcService.GetProdListRpc", in)
	out := new(Model.RpcResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RpcService service

type RpcServiceHandler interface {
	GetProdListRpc(context.Context, *Model.RpcRequest, *Model.RpcResponse) error
}

func RegisterRpcServiceHandler(s server.Server, hdlr RpcServiceHandler, opts ...server.HandlerOption) error {
	type rpcService interface {
		GetProdListRpc(ctx context.Context, in *Model.RpcRequest, out *Model.RpcResponse) error
	}
	type RpcService struct {
		rpcService
	}
	h := &rpcServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&RpcService{h}, opts...))
}

type rpcServiceHandler struct {
	RpcServiceHandler
}

func (h *rpcServiceHandler) GetProdListRpc(ctx context.Context, in *Model.RpcRequest, out *Model.RpcResponse) error {
	return h.RpcServiceHandler.GetProdListRpc(ctx, in, out)
}
